trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Use local agent 

variables:
  resourceGroupName: 'work-branch-test' 
  location: 'eastus'
  storageAccount1Name: 'st$(Build.SourceBranchName)1'
  storageAccount2Name: 'st$(Build.SourceBranchName)2'
  vmName: 'ubuntuVM'
  templateFolder: 'templates'
  
jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy Storage Accounts and Virtual Machine'
    steps:

      - checkout: self

      # Deploy Storage Account 1
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Storage Account 1'
        inputs:
          azureResourceManagerConnection: 'Azure subscription 1(3b6ddfaa-2788-46ca-b82d-c51e30360c61)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/$(templateFolder)/azure-storage/storage-arm-template.json'

      # Deploy Storage Account 2
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Storage Account 2'
        inputs:
          azureResourceManagerConnection: 'Azure subscription 1(3b6ddfaa-2788-46ca-b82d-c51e30360c61)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/$(templateFolder)/azure-storage/storage-arm-template.json'

      - script: |
          echo "##vso[task.setvariable variable=storageAccount1Name]$(storageAccount1Name)"
          echo "##vso[task.setvariable variable=storageAccount2Name]$(storageAccount2Name)"
        displayName: 'Set output variables'

      # Deploy VM
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy VM'
        inputs:
          azureResourceManagerConnection: 'Azure subscription 1(3b6ddfaa-2788-46ca-b82d-c51e30360c61)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/$(templateFolder)/azure-server/server-arm-template.json'
          csmParametersFile: '$(Build.SourcesDirectory)/$(templateFolder)/parameters/vm-parameters.json'
          overrideParameters: '-vmName $(vmName) -adminPassword $(adminPassword)'